### ISSUE TITLE
swapped self.wcs._naxis in make_noiseless_image?

### ISSUE THREAD

**Issue by lspitler** [AstroHuntsman/gunagala#18]
I think on line:

https://github.com/AstroHuntsman/gunagala/blob/7b6fcbfe892341cb4ec7a672ec4f04c064d2e866/gunagala/imager.py#L1562

The naxis should be swapped? Found this using rectangular image and square PSF.

**Comment by lspitler** [comment]
@bazkiaei I believe this is the Issue you're dealing with with the current PR?

**Comment by bazkiaei** [comment]
> @bazkiaei I believe this is the Issue you're dealing with with the current PR?

I think we fixed it within `Fix axis 18 WIP`.

**Comment by lspitler** [comment]
OK, @bazkiaei closing this issue. Though @AnthonyHorton feel free to re-open.

**Comment by AnthonyHorton** [comment]
@lee Would be good to confirm that #20 has indeed fixed this. It should have though.
