### ISSUE TITLE
something odd with offsets

### ISSUE THREAD

**Issue by lspitler** [AstroHuntsman/gunagala#19]
If one changes the pixellated PSF offset, it appears that the regions without PSF coverage flip between zero and nan. Difference these two images:

<img width="722" alt="screen shot 2018-06-12 at 3 10 45 pm" src="https://user-images.githubusercontent.com/1572325/41327290-7b93f9f8-6ef5-11e8-821b-e113d57ddb6d.png">
<img width="724" alt="screen shot 2018-06-12 at 3 10 55 pm" src="https://user-images.githubusercontent.com/1572325/41327292-7bc86a26-6ef5-11e8-87c1-7f18c5ceffb2.png">

**Comment by AnthonyHorton** [comment]
@lspitler Is this still happening?

**Comment by lspitler** [comment]
@AnthonyHorton not sure. @bazkiaei are you able to copy/paste the code above into a fresh jupyter notebook to test if you can reproduce changing the `offsets` input?

**Comment by bazkiaei** [comment]
I did not know by which data the above images are generated. I tried it with another simulation data and it is OK when I change the offset. I tried several combinations (including integers) for the offsets and presented two of them here. @lspitler @AnthonyHorton 
![screen shot 2018-11-22 at 2 32 26 pm](https://user-images.githubusercontent.com/40375207/48880279-d8b95e00-ee63-11e8-8b2d-8e13f15b6bd7.png)

**Comment by lspitler** [comment]
@bazkiaei can you used *exactly* the same offsets I used?

**Comment by bazkiaei** [comment]
@lspitler Of course, here it is:

![screen shot 2018-11-22 at 5 59 37 pm](https://user-images.githubusercontent.com/40375207/48886552-7ae73f00-ee80-11e8-8de7-15a7a573c2ef.png)

**Comment by lspitler** [comment]
@bazkiaei perfect, thanks! @AnthonyHorton closing this one as it seems to have gone away, perhaps due to the other issues we've found or maybe just matplotlib has changed?
