### ISSUE TITLE
Improve Pytest in test_psf.py

### ISSUE THREAD

**Issue by bazkiaei** [AstroHuntsman/gunagala#26]
There are some small jobs left to improve `test_psf.py` and since they are small jobs, they can be handled very soon.

**Comment by lspitler** [comment]
@bazkiaei good to do this soon while its still fresh. Do you need @AnthonyHorton 's input for this? Let me know if I can help.

**Comment by bazkiaei** [comment]
> @bazkiaei good to do this soon while its still fresh. Do you need @AnthonyHorton 's input for this? Let me know if I can help.

I am on it and I am in touch with @AnthonyHorton

**Comment by bazkiaei** [comment]
The `test_psf.py` is parametrised and decorated now. 
https://github.com/AstroHuntsman/gunagala/pull/28
